### ISSUE TITLE
Privacy leakage in "PutPrivateData" function in stubWrapper.go

### ISSUE THREAD

**Issue by pdchecker** [hyperledger-labs/cc-tools#46]
**Describe the bug**
Privacy leakage in "PutPrivateData" function in stubwrapper/stubWrapper.go

**To Reproduce**
1. Deploy stubWrapper.go, along with the PDC definition.
2. Invoke the PutPrivateData function to write the private data P to the PDC.
3. Fetch the block and find corresponding transaction.
4. The private data P can be found in "args" field

**Expected behavior**
The private data will be included in the transaction and all peers can access.

**Screenshots**
The private data is recorded in base64.
![image](https://github.com/hyperledger-labs/cc-tools/assets/169994828/381a7c11-0504-4f46-95d8-19be9044b738)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Hyperledger Fabric2.4.7

**Additional context**
The private data should be passed in the function via "GetTranscient"

**Comment by samuelvenzi** [comment]
Hey @pdchecker. Can you provide the way that you called the invoke of the transaction? Was it through the chaincode API or through command line? Either way, if you could provide the request payload or peer invoke command for us.

**Comment by pdchecker** [comment]
您的来信我已收到！祝您生活愉快！

**Comment by samuelvenzi** [comment]
My guess is that you did not call the API with args in transient form. I will close this due to inactivity. Feel free to reopen.
